version: '2.1'

orbs:
  android: circleci/android@2.0

workflows:
  test:
    jobs:
      - android/run-ui-tests:
          executor:
            name: android/android-machine
            tag: "2022.06.1"
          pre-steps:
            - run: "sdkmanager --update"
          matrix:
            parameters:
              system-image:
                - system-images;android-31;google_apis_playstore;x86_64
                - system-images;android-30;google_apis_playstore;x86_64
                - system-images;android-31;google_apis;x86_64
                - system-images;android-30;google_apis;x86_64
                - system-images;android-31;default;x86_64
                - system-images;android-30;default;x86_64
                # can't run 32-bit versions of below
                #- system-images;android-31;default;x86
                #- system-images;android-30;default;x86
                - system-images;android-29;default;x86
